### ISSUE TITLE
[Possible Bug?] Hotswap test "T" poses in game

### ISSUE THREAD

**Issue by MistressPlague** [Dean2k/A.R.E.S#1]
In game, the avatar is stuck in a T pose and the AV3 expressions are grayed out, implying no animator or descriptor, or a major issue in one or the other.

This could be unique to me, it'd need at least one other to test a generic hotswap.

EDIT: Debugged; issue seems to be from the animator from what I see? even parameterCount is 0 along with no runtimeAnimationController when it has numerous toggles.
Keep in mind that is correlation, it doesn't imply causation. More investigation is needed.

Another thing I notice is the viewpoint is the same as the loading avatar. And yes, i am testing without mods.

EDIT 2: From looking even further into it, the animator on the pedestal when selecting the avatar works perfectly; but it fails completely once switched into; lacking all needed things. Just weird.

**Comment by Dean2k** [comment]
Can you supply the avatar ID so i can test this.

**Comment by MistressPlague** [comment]
I would only provide that in private. Mistress Plague#0001
