### ISSUE TITLE
API Key?

### ISSUE THREAD

**Issue by WeirdcoreRabbit** [Dean2k/A.R.E.S#10]
I'm Confused..what to I put in the API key field, because without it I can't download it basically in no key mode
![Screenshot 2022-07-15 143655](https://user-images.githubusercontent.com/102920298/179289330-a0fc55c4-3284-4b1c-b654-947618e9d21e.png)
.

**Comment by ghost** [comment]
Join the discord (discord.gg/vrc-ares) and there are steps on how to get an API key.
