### ISSUE TITLE
Denied access to LatestLog.txt + ARES Version not detected in INI file

### ISSUE THREAD

**Issue by adoboing** [Dean2k/A.R.E.S#11]
![image](https://user-images.githubusercontent.com/98285417/182178934-55a358d4-4039-402e-93e3-cd4808ce63ea.png)
This happens every time I open the latest version, was just trying to put in my API key and restart

**Comment by ghost** [comment]
You didn't follow the Install instructions correctly and placed the files within your system 32 folder, this has extremely limited access
