### ISSUE TITLE
(falsely?) banned from server

### ISSUE THREAD

**Issue by krispwaffles** [Dean2k/A.R.E.S#13]
i was just making my way into the ARES discord server and i was filling out the verification needed in order to gain access to the server and i was then banned from the server on the spot. i don't know if i did something wrong or if it was just a false ban but whatever it is if it could be resolved soon i would greatly appreciate it. my discord that got banned was waffles#0589.

**Comment by ghost** [comment]
It was detected that you were attempting to join the server with one of your alternate accounts, its against our rules to have anything besides your main discord account within our discord server this is to limit keys in circulation and prevent ban evasion.

**Comment by krispwaffles** [comment]
okay thank you for letting me know, i appreciate your fast response
