### ISSUE TITLE
favorites bug thing

### ISSUE THREAD

**Issue by SimulatedSpirits** [Dean2k/A.R.E.S#2]
unable to change avatar after using avatar from ares favorites

**Comment by Dean2k** [comment]
Hi, i've just tried it and its working fine on my end, maybe the avatar you've favourited has gone private.

Try again but with a different avatar

**Comment by SimulatedSpirits** [comment]
ill check it may be a problem with one of my other clients running

**Comment by SimulatedSpirits** [comment]
it is working now after i turned off my pc maybe something idk but its fixed
