### ISSUE TITLE
"Log of your own avatars" does not work

### ISSUE THREAD

**Issue by WilliKriks** [Dean2k/A.R.E.S#3]
My avatars are not loading, which I usually use in Loger Ares... What to do with it is the most important?

**Comment by pi11ow** [comment]
Im having the same issue too, I've done everything by reinstalling, making sure Log file is in place. etc. Nothing seems to get it working

**Comment by WilliKriks** [comment]
solved, you need to remove the entire ARES GUI and reinstall
