### ISSUE TITLE
Quest VRCA Logging Broken???

### ISSUE THREAD

**Issue by UselessMage** [Dean2k/A.R.E.S#5]
could you possibly fix this or is it going to be gone forever

**Comment by ghost** [comment]
It's not a matter of fixing it, it literally can't be done anymore, VRChat no longer sends the quest asset url to PC even via Photon. This kinda fucky wuckys the sense of logging quest asset as a whole ;-;

**Comment by Sighyu** [comment]
Hahaha quest shit
