### ISSUE TITLE
what does no key mode mean

### ISSUE THREAD

**Issue by lickme1411** [Dean2k/A.R.E.S#8]
if you could help i dont know how to fix this but whenever i try to use ares its always says no key mode and i dont know how to fix it

**Comment by ghost** [comment]
> if you could help i dont know how to fix this but whenever i try to use ares its always says no key mode and i dont know how to fix it 

ARES API now reqires an API key, they are free can can be fetched via filing a ticket and being in our discord server, discord.gg/vrc-ares
