### ISSUE TITLE
I can't get an key

### ISSUE THREAD

**Issue by man2man3** [Dean2k/A.R.E.S#9]
You may remember me as Invalid#9851 aka "why are the avatars cubes" but anyway, i'm banned from the Largest boi server.. i'm sure you've taken notice of the abusive admin and handled it, but uh,, my issue is that i'm still banned.... so unban plzzz and thank you :. )

If your going to ask if there was a motive to my ban, my awnser to that is: the only reason i can think of getting banned from the server for is probly saying that the owner was rude, witch in my honest opinion i still hold true but given the chance can change, but i do agree on hes frustration as i now realize i was being a retard.. cuz i figured it out on my own! and i think i pinged a owner but i dont recall that being violation of rules but theres always a possibility of that being the cause ¯\\.-(ツ)-./¯

**Comment by ghost** [comment]
All bans are permanent, you were banned for repeatedly pinging staff and asking all questions in our FAQ even after being directed there and yes, that is in our rules, to read the FAQ before asking. When braught up you were I silting to staff members. They aren't obligated to help, I'm not obligated to help. This is a free service that we opt to maintain because we belive the community needs a tool like this, what this community does not need is asshats like you.

**Comment by man2man3** [comment]
first of all, if you directed me to the FAQ and i was still asking questions about it then CLEARLY what ever the directions was there to fix it was NOT WORKING, to professionally handle that situation is to either give me another option or tell me you dont know how to fix this issue.. of witch NEITHER METHODS WERE USED, you basically told me to "Figure it out". second what the hell dose "silting" mean. third of all ONCE AGAIN i come here for support and you gotta be a dick about it, Fuck you and Fuck your services, you fucking jerk

**Comment by man2man3** [comment]
god damn thats what i get for trying to set our past asside and be nice...

**Comment by ghost** [comment]
Set your past aside? All you have done is show absolutely everybody how entitled you are.

**Comment by man2man3** [comment]
by asking questions?... i bet your real proud of that one

**Comment by man2man3** [comment]
my point is you were being a dick about it and instead of being a part of a support team, you screwed me over

**Comment by man2man3** [comment]
and also im not trying to "show everybody" this is my only form of communication since.. y'know you banned me from the only other methed

**Comment by ghost** [comment]
Entitlement at its finest, we screwed YOU over, you wanted a fix, you were directed to the solution, when it didn't work you opted to ask repeatedly to the point of spamming, you are acting as if you are owed a copy of ARES. You aren't owed anything, under no circumstances am I or any ARES member REQUIRED to provide support. You are openly screaming about how much of an absolute fool you are. Do something, anything better with you time, rather then screaming on our GitHub issues because you aren't intelligent enough to use a free, open source, fully documented program with a myriad of guides.

**Comment by man2man3** [comment]
you dont get to choose what im entitled to as far as i know i am entited to call you out if you doing something wrong as i am doing here. any person would have enough brains cells to tell a person to stop "Spamming", if you had done so.. i wouldn't have gotten banned therefor your bad moderation is to blame. i wouldn't be "screaming" at you if you weren't being an asshole. i dont want a copy of ares, all i wanted is a simple fucking key.. thats it.. but your additude is preventing that

**Comment by ItzShy** [comment]
use spell check please

**Comment by ghost** [comment]
You are owed nothing, with all disrespect shut the fuck up.

**Comment by teddyowo** [comment]
theres digital karens now? we're so fucked.

**Comment by ScrimCreations** [comment]
> you dont get to choose what im entitled to as far as i know i am entited to call you out if you doing something wrong as i am doing here.

Why are you being an entitled karen?

**Comment by LilDevilLuce** [comment]
> you dont get to choose what im entitled to as far as i know i am entited to call you out if you doing something wrong as i am doing here. any person would have enough brains cells to tell a person to stop "Spamming", if you had done so.. i wouldn't have gotten banned therefor your bad moderation is to blame. i wouldn't be "screaming" at you if you weren't being an asshole. i dont want a copy of ares, all i wanted is a simple fucking key.. thats it.. but your additude is preventing that

You're kinda cringe stfu digi karen. go rage on facebook or something lmao

**Comment by Awarela** [comment]
> you dont get to choose what im entitled to as far as i know i am entited to call you out if you doing something wrong as i am doing here. any person would have enough brains cells to tell a person to stop "Spamming", if you had done so.. i wouldn't have gotten banned therefor your bad moderation is to blame. i wouldn't be "screaming" at you if you weren't being an asshole. i dont want a copy of ares, all i wanted is a simple fucking key.. thats it.. but your additude is preventing that

Yo you crying to much Ima crossban you on my servers cause It would be a pain to have you with that actitude on my server, stop crying and doing apeshit on a github issue tab for getting banned for being a brainlet, you just gonna get worse things if you keep screaming like a 12 yo questie...

**Comment by CloudyBoop** [comment]
Kys fag

**Comment by man2man3** [comment]
who the hell are these people?

**Comment by man2man3** [comment]
> > you dont get to choose what im entitled to as far as i know i am entited to call you out if you doing something wrong as i am doing here. any person would have enough brains cells to tell a person to stop "Spamming", if you had done so.. i wouldn't have gotten banned therefor your bad moderation is to blame. i wouldn't be "screaming" at you if you weren't being an asshole. i dont want a copy of ares, all i wanted is a simple fucking key.. thats it.. but your additude is preventing that
> 
> Yo you crying to much Ima crossban you on my servers cause It would be a pain to have you with that actitude on my server, stop crying and doing apeshit on a github issue tab for getting banned for being a brainlet, you just gonna get worse things if you keep screaming like a 12 yo questie...

at least ik the correct definition of "crying" you use it like a 8 year old slender on roblox. stfu nobody asked you to be here.
also why would i give af about your servers? i dont even know who the hell you are.

**Comment by ghost** [comment]
Sumbody maaad

**Comment by man2man3** [comment]
where the hell your freinds come from?

**Comment by ghost** [comment]
They saw a dumbass, so they came out of the wood works ;-;

**Comment by man2man3** [comment]
damn you needed to call in support 💀

**Comment by ghost** [comment]
Not really, they just heard the circus in town, came to watch.

**Comment by man2man3** [comment]
dought it, anyways problems solved i got an alt in the server so i got a key, no thanks

**Comment by ghost** [comment]
Happy to know our tools good enough for you to go through the trouble

**Comment by man2man3** [comment]
not even gonna lie, the whole ares thing is kinda dope.. just not worth all of this

**Comment by ghost** [comment]
Well just a matter of time before a prune or key check gets ya, I would use it alot while ya can

**Comment by man2man3** [comment]
i dont need it anymore, i got what i needed. still broken of course but im tring to learn a bit of the unity stuff so i can fix it

**Comment by ghost** [comment]
Happy to hear

**Comment by ItzShy** [comment]
> 

"Dought it"

**Comment by man2man3** [comment]
asked = false, get lost

**Comment by ItzShy** [comment]
> 

lmao cringe lord moment, cant even spell

**Comment by teddyowo** [comment]
> asked = false, get lost

last i checked a public github issue
so, in turn
asked == true

**Comment by man2man3** [comment]
asked = didn't, 💀

**Comment by ItzShy** [comment]
spelling = cant

**Comment by man2man3** [comment]
> spelling = cant

punctuation = cant

**Comment by teddyowo** [comment]
> asked = didn't, 💀

github issue = public
your opinion = invalid
your life = worthless
kill yourself = now

**Comment by man2man3** [comment]
cant forget the capitals

**Comment by ItzShy** [comment]
you forgot both

**Comment by man2man3** [comment]
and? this isn't an essey, is a conversation of dumb asses

**Comment by teddyowo** [comment]
> and? this isn't an essey, is a conversation of dumb asses

so your point on needing them is invalid, silly

**Comment by ItzShy** [comment]
You're really taking the time to reply to all of these, what a sad life you lead.

**Comment by man2man3** [comment]
> > and? this isn't an essey, is a conversation of dumb asses
> 
> so your point on needing them is invalid, silly

wasn't the point

**Comment by teddyowo** [comment]
> You're really taking the time to reply to all of these, what a sad life you lead.

frrrrrrr

**Comment by teddyowo** [comment]
> > > and? this isn't an essey, is a conversation of dumb asses
> > 
> > 
> > so your point on needing them is invalid, silly
> 
> wasn't the point

well now it is the point

**Comment by man2man3** [comment]
> You're really taking the time to reply to all of these, what a sad life you lead.

acctually im doing this for fun, its not common i get a chance to be toxic

**Comment by ItzShy** [comment]
That's depressing tbh

**Comment by man2man3** [comment]
good for you

**Comment by teddyowo** [comment]
> > You're really taking the time to reply to all of these, what a sad life you lead.
> 
> acctually im doing this for fun, its not common i get a chance to be toxic

so far its less toxic, and more just sad

**Comment by ItzShy** [comment]
I can tell you have a total of 0 friends

**Comment by man2man3** [comment]
> I can tell you have a total of 0 friends

i can tell you have a total of 0 fathers

**Comment by man2man3** [comment]
l

**Comment by ItzShy** [comment]
1 actually

**Comment by man2man3** [comment]
dought

**Comment by teddyowo** [comment]
> dought

doubt*

**Comment by man2man3** [comment]
> > > You're really taking the time to reply to all of these, what a sad life you lead.
> > 
> > 
> > acctually im doing this for fun, its not common i get a chance to be toxic
> 
> so far its less toxic, and more just sad

did i ask if you had depression?

**Comment by ItzShy** [comment]
Man's got called out 3x for spelling and hasn't used the spell check built into his pc 💀

**Comment by man2man3** [comment]
> > dought
> 
> doubt*

do i really need to say it again?

**Comment by man2man3** [comment]
> Man's got called out 3x for spelling and hasn't used the spell check built into his pc 💀

i dont have spell check, fucking dumbass get off your school chromebook

**Comment by teddyowo** [comment]
> > Man's got called out 3x for spelling and hasn't used the spell check built into his pc 💀
> 
> i dont have spell check, fucking dumbass get off your school chromebook

his computer costs more than your house, relax

**Comment by man2man3** [comment]
> > > Man's got called out 3x for spelling and hasn't used the spell check built into his pc 💀
> > 
> > 
> > i dont have spell check, fucking dumbass get off your school chromebook
> 
> his computer costs more than your house, relax

not my problem hes so addicted to gameing to spend a few thousand dollors on a pc

**Comment by ItzShy** [comment]
> > Man's got called out 3x for spelling and hasn't used the spell check built into his pc 💀
> 
> i dont have spell check, fucking dumbass get off your school chromebook

He says while on a web browser that can tell you how to spell a word if you're unsure

**Comment by teddyowo** [comment]
> > > > Man's got called out 3x for spelling and hasn't used the spell check built into his pc 💀
> > > 
> > > 
> > > i dont have spell check, fucking dumbass get off your school chromebook
> > 
> > 
> > his computer costs more than your house, relax
> 
> not my problem hes so addicted to gameing to spend a few thousand dollors on a pc

not my problem you cant afford said few thousand dollars

**Comment by man2man3** [comment]
> > > Man's got called out 3x for spelling and hasn't used the spell check built into his pc 💀
> > 
> > 
> > i dont have spell check, fucking dumbass get off your school chromebook
> 
> He says while on a web browser that can tell you how to spell a word if you're unsure

imagine useing chrome? L no wonder you need to spend that much on a pc

**Comment by ghost** [comment]
Issue locked, this can stop riiight here
